#define LOWERS "abcdefghijklmnopqrstuvwxyz"
#define DIGITS "0123456789"
#define UPPER "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
#define PUNCTUS ",.;:!?"
#define BRACKETS "(){}[]"
#define QUOTES "'"""
#define OTHER "`~@#$%^&*|/\><-=_+\n"